// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfW0OKdGKVW1T37e5827yiC5kyJV18wkI',
    appId: '1:272487133769:web:8c2379d9e98e008da4c598',
    messagingSenderId: '272487133769',
    projectId: 'travel-app-burrahh',
    authDomain: 'travel-app-burrahh.firebaseapp.com',
    storageBucket: 'travel-app-burrahh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhXKH2Lzak4_ivBC01E7phal-XGpROx8',
    appId: '1:272487133769:android:10d42ea49152700ca4c598',
    messagingSenderId: '272487133769',
    projectId: 'travel-app-burrahh',
    storageBucket: 'travel-app-burrahh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxfqkiPn-pgL2gOWDsw933a8pBwcGcjWM',
    appId: '1:272487133769:ios:d9ecb98b5ae95749a4c598',
    messagingSenderId: '272487133769',
    projectId: 'travel-app-burrahh',
    storageBucket: 'travel-app-burrahh.appspot.com',
    iosBundleId: 'com.example.travellio',
  );
}
